name: response
description: Flutter application for disaster management.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #  UI specific:
  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.8
  drop_cap_text: ^1.0.7
  flutter_screenutil: ^2.3.1

  #  Utilities
  easy_localization: ^2.3.2
  validators: ^2.0.0
  url_launcher: ^5.5.0
  share: '>=0.6.4+3 <2.0.0'
  intl:
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1

  # Google Services:
  provider: ^4.3.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  flutter_dialogflow: ^0.1.2

  google_maps_flutter: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/json/credentials.json
#    - language/en.json
#    - language/hi.json
#    - language/mr.json

  fonts:
    - family: BungeeShade
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf

    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne.ttf

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf

    - family: Anton-Regular
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

    - family: PlayfairDisplay-Bold
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf

    - family: PlayfairDisplay-Regular
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf

#    Custom Icons
    - family: Maps
      fonts:
        - asset: assets/fonts/Maps.ttf

    - family: News
      fonts:
        - asset: assets/fonts/News.ttf

    - family: Idea
      fonts:
        - asset: assets/fonts/Idea.ttf

    - family: Share
      fonts:
        - asset: assets/fonts/Share.ttf

    - family: ArrowFront
      fonts:
        - asset: assets/fonts/ArrowFront.ttf

    - family: HeartIcon
      fonts:
        - asset: assets/fonts/HeartIcon.ttf

    - family: Emergency
      fonts:
        - asset: assets/fonts/Emergency.ttf

    - family: DrawerIcon
      fonts:
        - asset: assets/fonts/DrawerIcon.ttf


